library(tibble)
library(plyr)
tsuccess <- as.data.frame(t(success))
myDF <- tibble(year=1970:2010,mean40year = laply(tsuccess,mean, na.rm=T),
               sum40year = laply(tsuccess,sum,na.rm=T))
laply(tsuccess,mean, na.rm=T)
colMeans(tsuccess, na.rm=T)
class(tsuccess$V1)
myvec <- paste('V',1:41,sep = '')
tsuccess[myvec] <- sapply(tsuccess[myvec],as.character)
tsuccess[myvec] <- sapply(tsuccess[myvec],as.numeric)
median(tsuccess$V1[tsuccess$V1 > 0], na.rm=T)
